### 주민 등록
POST /residents HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Content-Encoding: utf-8

{
  "name": "테스트",
  "registrationNumber" : "221202-3111111",
  "gender" : "남",
  "birthDate" : "2022-12-02 12:01:00",
  "birthPlace": "병원",
  "registrationAddress": "경남 창원시 마산회원구 중리상곡로 114"
}

### 주민 수정
PUT /residents/8 HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Content-Encoding: utf-8

{
  "name": "변경 이후",
  "registrationNumber" : "221202-3111111",
  "gender" : "여",
  "birthDate" : "2022-12-02 12:01:00",
  "birthPlace": "자택"
}

### 가족관계 등록
POST /residents/7/relationship HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Content-Encoding: utf-8

{
  "familySerialNumber": 8,
  "relationShip" : "child"
}

### 가족관계 수정
PUT /residents/7/relationship/8 HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Content-Encoding: utf-8

{
  "relationShip" : "father"
}

### 가족관계 삭제
DELETE /residents/7/relationship/8 HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Content-Encoding: utf-8
